# -*- coding: utf-8 -*-
"""Exercises_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ncb9SuTLc-o9-fcyktcZikCPGXiwvHyX
"""

t=3
v=343

s=v*t
print(s)

import math
a=3
b=-4
c=-10

delta=b**2 - 4*a*c

x1=(-b + math.sqrt(delta))/(2*a)

x2=(-b - math.sqrt(delta))/(2*a)

print('As raízes são')
print(x1,x2)

tg = 5/0.5

print(tg)

M=70
A=1.79

IMC=M/A**2

print(IMC)

import math

g=9.8
h=3
v=math.sqrt(2*g*h)

print('A velocidade ao chegar no solo é:', v)


t=math.sqrt(2*h/g)

print('O tempo de queda é:', t)









